name: Lint and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Black
      run: |
          pipenv run format
    - name: Commit autopep8 changes
      if: steps.Black.outputs.exit-code == 1
      run: |
        git config --global user.name 'koerners'
        git config --global user.email 'git@skoerner.com'
        git commit -am "Automated formatting fixes"
        git push
    
    - name: Analysing the code with pylint
      if: steps.Black.outputs.exit-code == 0
      run: |
        pipenv run lint
    - name: Running tests
      if: steps.Black.outputs.exit-code == 0
      run: |
        pipenv run test
